Handle errors globally with Error Middleware and React Error Boundary
ImagingDataCommons/slim pull request #134
Opened 2022-11-19 05:45 UTC by GitanjaliChhetri

Summary of the PR:
1. Handle all known errors from dicomweb-client, dcmjs, dmv, and the app itself using _ErrorMiddleware.js_ (an extension of pubsub pattern). Errors are now funneled to the onError event. User is notified based on the notification type (configurable, toast and config for now) for each source of error. 
2. A debug info button is added to the header component. It is subscribed to the onError event and keeps a record of all 3 types of error - Server, Data Parsing, and Viewer.
3. _ErrorBoundary.tsx_ :  The React error boundary component is responsible for catching (unexpected) rendering errors and displays a modal window as a fallback component. It is currently wrapped around the App component.

![image](https://user-images.githubusercontent.com/112136540/202836427-1e9f1178-c31d-4abc-8b6b-07c97873c185.png)
![image](https://user-images.githubusercontent.com/112136540/202836432-1521ccc8-16fd-4c0d-a63c-b18514dc39de.png)
![image](https://user-images.githubusercontent.com/112136540/202836439-be1f8959-0d71-42f5-86fb-183e1674679b.png)

2022-11-21 11:02 UTC, igoroctaviano requested changes
Left a few comments. Please prioritize the removal of all formatting changes so we have a clearer pull request to review.

Thank you in advance.

2022-11-21 11:02 UTC, igoroctaviano commented on src/data/slides.tsx
> +          ErrorMiddleware.onError('slim',
Create enums for these values instead of using hardcoded strings like 'slim'. 
e.g. NotificationMiddlewareContext.SLIM;

2022-11-22 00:59 UTC, GitanjaliChhetri commented on src/App.tsx
> +import OidcManager from "./auth/OidcManager";
fixed.

2022-11-22 00:59 UTC, GitanjaliChhetri commented on src/DicomWebManager.ts
> +      return await this.stores[0].client.storeInstances(options);
fixed.

2022-11-22 00:59 UTC, GitanjaliChhetri commented on src/components/ErrorHandler/CustomPubSub.js
> +const _lastSubscriptionId = Symbol('lastSubscriptionId');
done.

2022-11-22 01:00 UTC, GitanjaliChhetri commented on src/components/ErrorHandler/ErrorMiddleware.js
> +const NotificationSourceDefinition = {
Done. Renamed and moved under a new services folder.

2022-11-22 01:00 UTC, GitanjaliChhetri commented on src/data/slides.tsx
> +          ErrorMiddleware.onError('slim',
Done.

2022-11-23 13:40 UTC, igoroctaviano requested changes

2022-11-23 13:40 UTC, igoroctaviano commented on src/components/Header.tsx
> +    NotificationMiddleware.subscribe('onError', onErrorHandler)
Use event enum here instead of hardcoded value.

2022-11-23 13:40 UTC, igoroctaviano commented on src/services/NotificationMiddleware.js
> +  OnError: 'onError'
Change to NotificationMiddlewareEvents.

2022-11-23 13:40 UTC, igoroctaviano commented on src/services/NotificationMiddleware.js
> +      notificationType: 'toast',
Maybe the NotificationType could be an enum as well? Also the NotificationCategory?

2022-11-23 13:40 UTC, igoroctaviano commented on src/services/NotificationMiddleware.js
> +      case 'toast':
Then you could use the NotificationType enum here.

2022-11-23 13:40 UTC, igoroctaviano commented on src/components/OpticalPathItem.tsx
> +    } catch (error: any) {
Do we know this error type by advance or it needs to be any?

2022-11-23 23:47 UTC, GitanjaliChhetri commented on src/components/OpticalPathItem.tsx
> +    } catch (error: any) {
We don't have error interceptor for the dcmjs library, that's why the any type, which is later handled by the _Notificationmiddleware.js_ . The any type was used in all catch statements in _SlideViewer.tsx_ .

2022-11-25 19:15 UTC, igoroctaviano reviewed
@GitanjaliChhetri code LGTM. Feel free to assign it to @hackermd for final review/approval.

2022-11-28 16:31 UTC, GitanjaliChhetri commented
@hackermd I am unable to add you as one of the reviewers. Please know this PR is ready for your review. Thanks!

2022-12-12 02:48 UTC, hackermd requested changes
@GitanjaliChhetri, thanks so much for this great work!

I only have a few comments regarding coding style and questions regarding naming things.

2022-12-12 02:48 UTC, hackermd commented on src/components/Header.tsx
> +      NotificationMiddlewareEvents.OnError, onErrorHandler)
```suggestion
    NotificationMiddleware.subscribe (
      NotificationMiddlewareEvents.OnError,
      onErrorHandler
    )
```

2022-12-12 02:48 UTC, hackermd commented on src/services/NotificationMiddleware.js
>          console.error(`An error occured in ${category}`, error)
```suggestion
        console.error(`A ${category} error occurred: `, error)
```

2022-12-12 02:48 UTC, hackermd commented on src/services/NotificationMiddleware.js
>          console.error(`An error occured in ${category}`, error)
```suggestion
        console.error(`A ${category} error occurred: `, error)
```

2022-12-12 02:48 UTC, hackermd commented on src/services/NotificationMiddleware.js
> +  PARSING: 'Parsing'
I wonder whether we should rename those from "Server", "Viewer", and "Parsing" to "Communication", "Display / User Interaction", and "Encoding / Decoding". I feel those terms would better represent the nature of the errors and would make it easier to understand what kind of error occurred rather than where the error occured.

For example, an error in a function of the dicomweb-client package would certainly be related to data communication, but it wouldn't be obvious whether the server or the client were to blame without taking HTTP status codes into account.

2022-12-12 02:48 UTC, hackermd commented on src/services/NotificationMiddleware.js
> +}
Since `TOAST` will also log the error to the console, I wonder whether we need `NotificationType` or whether we should just use a `toast` option of Boolean data type. Thoughts?

2022-12-12 10:07 UTC, GitanjaliChhetri commented on src/services/NotificationMiddleware.js
> +}
Thank you for the review, @hackermd .
It's useful to have the `NotificationType` option, as later for certain errors if we require user action, we can display a Modal/Dialog box. What do you think?

I haven't handled the errors thrown from the OidcManager class.
Should this one be just logged to console? https://github.com/herrmannlab/slim/blob/33ccd128f6f9c167dc6c0acdba4eac61bfa0ef83/src/auth/OidcManager.tsx#L71
How about the other 4 errors thrown from this class?

2022-12-12 10:10 UTC, GitanjaliChhetri commented on src/services/NotificationMiddleware.js
> +  PARSING: 'Parsing'
Yes, it makes sense. I will update them to the suggested names.

2022-12-12 13:18 UTC, hackermd commented on src/services/NotificationMiddleware.js
> +}
> Should this one be just logged to console?

This error was not thrown, but only logged to the console. Therefore, I would not intercept it. It should be fine to just capture the error at the end of the auth flow upon failure of authentication or authorization.

2022-12-12 13:19 UTC, hackermd commented on src/services/NotificationMiddleware.js
> +  PARSING: 'Parsing'
Instead of "Display / User Interaction", we could also simply use "Visualization".

2022-12-12 13:28 UTC, hackermd commented on src/services/NotificationMiddleware.js
> +  PARSING: 'Parsing'
One issue with this approach is, however, that the source of the error doesn't necessary help us to determine whether an error was related to visualization of encoding/decoding, since both the dicom-microscopy-viewer library and the slim application encode/decode data.

Should we introduce custom error types by subclassing the `Error` class? We could do this in the library and the application. We could define a `DICOMwebError`, a `DICOMError`, etc.

2022-12-20 16:35 UTC, GitanjaliChhetri commented on src/services/NotificationMiddleware.js
> +  PARSING: 'Parsing'
Resolved in the latest commit.
Custom error class is added and notification type is based on the custom error type.

2023-01-19 22:40 UTC, GitanjaliChhetri commented
@hackermd I have addressed the requested changes. Please let me know if this can be merged? Thank you.

2023-01-27 21:06 UTC, fedorov commented
@hackermd if you could let us know when you might have time to look into this, it would be helpful!

2023-01-28 11:40 UTC, hackermd requested changes
@GitanjaliChhetri it's an elegant implementation. Please address the coding style issues and make sure the automated tests pass. Then we should be ready to merge.

2023-02-18 11:14 UTC, hackermd commented on src/components/AnnotationGroupItem.tsx
> +  handleOpacityChange (value: any): void {
Why change all of the types to `any`?

2023-04-03 15:26 UTC, igoroctaviano commented
@hackermd comments addressed. Can you please re-review? also, looks like the deploy gh-pages are not working. I think its because of action permissions. https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot

2023-04-13 06:32 UTC, hackermd approved these changes
Thank you very much @igoroctaviano!

2023-04-13 06:36 UTC, hackermd commented
> looks like the deploy gh-pages are not working. I think its because of action permissions. https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot

Not sure why this is happening. The settings are correct and it should work. Maybe a quirk related to the moving of the repository to the ImagingDataCommons organization. Could this be an issue with a global org-wide setting?

2023-04-13 06:37 UTC, merged