feat - 194: ROI class based color settings
ImagingDataCommons/slim pull request #227
Opened 2024-08-15 17:02 UTC by pedrokohler

Adding the ability to edit ROI colors based on their categories and types. Solves https://github.com/ImagingDataCommons/slim/issues/194.

2024-08-19 19:13 UTC, fedorov commented
Looks great testing with https://healthcare.googleapis.com/v1/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/annotated_rms-original-and-annotations-wc-temp-20240122/dicomWeb (specifically, RMS2455 is a good example).

Few suggestions:
* Can you populate default colors to allow differentiation between different types? 
* It is nice that you show SCT codes in tooltips for types - can you do the same for categories?
![image](https://github.com/user-attachments/assets/e6f8f065-e03e-4e7d-9ffb-10d1d89ef8a8)

2024-08-20 13:43 UTC, pedrokohler commented
@fedorov 

> * It is nice that you show SCT codes in tooltips for types - can you do the same for categories?

Isn't it showing on your end? For me it shows

![image](https://github.com/user-attachments/assets/b2f5cf29-2ac6-42e4-b863-994afe4a29a9)

Or do you mean something else?

> Can you populate default colors to allow differentiation between different types?

I'll work on this.

2024-08-20 15:12 UTC, fedorov commented
> Isn't it showing on your end? For me it shows

Indeed, it does show! I guess I was confused by the colors. Why is category black and type green-blue? I think all should be black

2024-08-28 15:11 UTC, pedrokohler commented
@fedorov you can check the changes you required here

https://idc-external-006.web.app/

2024-08-28 15:41 UTC, fedorov commented
@pedrokohler this is perfect, great work! Good to go from my perspective.

2024-08-28 16:23 UTC, igoroctaviano requested changes
First iteration, few questions!

2024-08-28 16:23 UTC, igoroctaviano commented on src/components/AnnotationCategoryList.tsx
> +  annotations,
I see a bunch of renaming, why we changed from annotationGroups to annotations here?

2024-08-28 16:23 UTC, igoroctaviano commented on src/components/AnnotationGroupItem.tsx
> +    uid: string
Why changing names here?

2024-08-28 16:23 UTC, igoroctaviano commented on src/components/SlideViewer.tsx
> +    const strokeColor = styleOptions.color ?? [0, 0, 0]
Extract the colors and opacity into named consts e.g. DEFAULT_OPACITY = 0.4 and DEFAULT_STROKE_COLOR = [0, 0, 0]

2024-08-28 16:23 UTC, igoroctaviano commented on src/components/SlideViewer.tsx
> +        [255, 158, 64],
Extract to enum outside functions

2024-08-28 16:23 UTC, igoroctaviano commented on src/components/SlideViewer.tsx
> +          opacity: 0.4
Extract to enums (seems like a repetitive 0.4 default value)

2024-08-28 19:04 UTC, pedrokohler commented on src/components/AnnotationCategoryList.tsx
> +  annotations,
Because it's not about annotation groups anymore, rather it's about ROIs and in the future this will also encompass annotation groups as well. To leave it more generic, I decided to call it simply "annotations".

2024-08-28 19:04 UTC, pedrokohler commented on src/components/AnnotationGroupItem.tsx
> +    uid: string
Same as above.

2024-08-29 01:17 UTC, igoroctaviano commented
<img width="1683" alt="Screenshot 2024-08-28 at 22 14 37" src="https://github.com/user-attachments/assets/b3e1f1c3-5ac7-4977-959d-1da7f536a084">

@pedrokohler can you please use the link below and check if you can replicate this error?

https://healthcare.googleapis.com/v1beta1/projects/idc-external-031/locations/us-east1/datasets/2d-bulk-ann/dicomStores/2d-bulk-ann/dicomWeb

2024-08-29 01:17 UTC, igoroctaviano commented
@pedrokohler Same error trying this one: https://healthcare.googleapis.com/v1beta1/projects/idc-external-031/locations/us-central1/datasets/pan-cancer-example-bulk-anns-2024-01-18/dicomStores/pan-cancer-example-bulk-anns-2024-01-18/dicomWeb

2024-08-29 01:22 UTC, igoroctaviano commented on src/components/AnnotationCategoryList.tsx
> +  annotations,
If your change makes the component reusable by other parts of the code, such as annotation groups, I recommend updating those parts to use the same component to avoid duplication. Alternatively, you could revert these changes and focus only on what's needed to complete the current task (ROI class-based color settings).

2024-08-29 12:10 UTC, pedrokohler commented on src/components/AnnotationCategoryList.tsx
> +  annotations,
the name annotation group is wrong, it should encompass both annotation groups and roi's

2024-08-29 13:04 UTC, igoroctaviano requested changes
Almost there! I notifed the following issue:
- Open the study
- Don't activate any ROI
- Go to the categories section but don't select any
- Change the color of one of the categories without activating
- The annotation is not visible but the category check is not checked

2024-08-29 13:49 UTC, igoroctaviano approved these changes
LGTM

2024-08-29 13:49 UTC, merged