feat: dicom tag browser
ImagingDataCommons/slim pull request #248
Opened 2024-10-29 12:58 UTC by igoroctaviano

- Add DICOM tag browser #228

<img width="1211" alt="Screenshot 2024-10-29 at 09 51 09" src="https://github.com/user-attachments/assets/82bcf290-f570-4ea6-b3a6-2ca19f4b670b">

2024-10-29 14:36 UTC, fedorov commented
Nice! Can you by any chance make sequences collapsible? (or may be they are collapsible already?)

2024-10-30 12:47 UTC, pedrokohler requested changes
Few suggestions and questions.

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagBrowser.css
We've been using the style property of the components as the standard way of styling for this project. Can't we keep it that way?

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +import moment from 'moment'
Moment is not an explicit project dependency. If we were to use it, it would have to be added in the project dependencies. 

Also moment is depecrated and is no recommended any more by the authors, take a look: https://momentjs.com/docs/#/-project-status/

If we are going to add a new time library in our project I recommend ditching moment and using one of the alternatives they recommend, such as Luxon.

2024-10-30 12:47 UTC, pedrokohler commented on src/components/CaseViewer.tsx
> -class Viewer extends React.Component<ViewerProps, ViewerState> {
Excellent idea getting rid of this class component. I'd like to suggest we ask Andrey to create a ticket and allow us a few hours to refactor the whole project to move it to the more modern approach of using hooks and function components. There's still a lot of class components in this project.

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +// Move these functions outside the component
outdated comment?

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +  images: any[]
I'm assuming it's complicated to add a more precise type. If it's not, then let's add it. Otherwise just ignore this.

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +}
If it's exactly the same as a TreeNode why not just use it instead and avoid unnecessary complexity?

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagTable.tsx
> +// @ts-nocheck
Why we adding that?

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagTable.tsx
> +        'bg-secondary-dark ohif-scrollbar flex w-full flex-row overflow-y-scroll'
ohif-scrollbar?

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/DicomTagTable.tsx
In this file we're using tailwind classes which is yet another styling strategy. I suggest we stick with one single styling strategy, namely the current project standard which is using the style property of the component.

2024-10-30 12:47 UTC, pedrokohler commented on src/components/DicomTagBrowser/dicomTagUtils.ts
> +// @ts-nocheck
Why?

2024-10-30 12:47 UTC, pedrokohler commented on src/components/Header.tsx
> +  clients: any
Please add type

2024-10-30 12:47 UTC, pedrokohler commented on src/hooks/useSlides.ts
> +}
These comments tend to get outdated quickly. I like avoiding comments unless they're strictly necessary.

2024-10-30 13:59 UTC, igoroctaviano commented on src/components/CaseViewer.tsx
> -class Viewer extends React.Component<ViewerProps, ViewerState> {
Thats the plan with the grant proposal, its in progress

2024-10-30 14:02 UTC, igoroctaviano commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +import moment from 'moment'
Updated! thx.

2024-10-30 14:02 UTC, igoroctaviano commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +// Move these functions outside the component
Updated! thx.

2024-10-30 14:02 UTC, igoroctaviano commented on src/components/DicomTagBrowser/DicomTagBrowser.tsx
> +}
Updated! thx.

2024-10-30 14:02 UTC, igoroctaviano commented on src/components/DicomTagBrowser/DicomTagTable.tsx
> +        'bg-secondary-dark ohif-scrollbar flex w-full flex-row overflow-y-scroll'
Updated! thx.

2024-10-30 14:02 UTC, igoroctaviano commented on src/components/Header.tsx
> +  clients: any
Updated! thx.

2024-10-30 14:02 UTC, igoroctaviano commented on src/hooks/useSlides.ts
> +}
Updated! thx.

2024-10-30 14:03 UTC, igoroctaviano commented on src/components/DicomTagBrowser/DicomTagTable.tsx
Updated! thx.

2024-10-30 22:39 UTC, igoroctaviano commented on src/components/DicomTagBrowser/DicomTagBrowser.css
Updated to keep css to a minimum. (Only overwrites to antd)

2024-10-30 22:39 UTC, igoroctaviano commented
@pedrokohler changes made, please review and test it please.

2024-10-31 11:33 UTC, pedrokohler approved these changes
Looks great.

2024-10-31 12:33 UTC, pedrokohler approved these changes
LGTM

2024-10-31 12:58 UTC, merged